class GitPackageIndexError(Exception): ...


class ConfigError(GitPackageIndexError): ...


class BuilderError(GitPackageIndexError): ...


class GitError(GitPackageIndexError): ...


class PackageNotFoundError(GitPackageIndexError): ...
